version: '3.8'

name: rssbot
services:
  bot:
    build: .
    pull_policy: always
    # image: ghcr.io/brawl345/rssbot:latest
    restart: always
    env_file: .env

  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_RANDOM_ROOT_PASSWORD: true
    ports:
      - '33060:3306'
    volumes:
      - 'rssbot-db:/var/lib/mysql'
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3

volumes:
  rssbot-db:
    name: rssbot-db
